//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Acount { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Avart { get; set; }
        public int Grade { get; set; }
        public string Sign { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Room { get; set; }
    }
}
